export const ATTEMPT_LOGIN = "ATTEMPT_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const FETCH_PLANETS = "FETCH_PLANETS";
export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";
export const FETCH_PLANETS_ERROR = "FETCH_PLANETS_ERROR";
